### ISSUE TITLE
this.array[i] instead of this[i]

### ISSUE THREAD

**Issue by Yaffle** [jasondavies/jsbn#4]
seems, performance of jsbn version from "Octane" is much better:
https://code.google.com/p/octane-benchmark/source/browse/latest/trunk/crypto.js?r=28
The difference is not big, seems: to store magnitude it uses "this.array".

Same optimization is used in "forge" - https://github.com/digitalbazaar/forge/blob/master/js/jsbn.js

**Comment by jasondavies** [comment]
Sorry for the delay!  This repository was originally intended as a straight mirror of the original jsbn by Tom Wu: <http://www-cs-students.stanford.edu/~tjw/jsbn/>.

I have attempted to upstream a few patches in the past but received no reply.

There is now a better-maintained mirror along with NPM package: <https://www.npmjs.com/package/jsbn> so feel free to report any improvements there, if you haven't done so already.
